In [1]:
import numpy as np 
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [2]:
x

array([[1., 0.],
       [0., 0.]])

In [3]:
y

matrix([[1., 1.],
        [2., 0.]])

In [4]:
import numpy as np
a = np.array([1,2, 3, []]) 
a[-1].append(4)
a[-1].append(5)
print(len(a))

4


In [6]:
import numpy as np 
a = np.zeros((2,2))
b = np.eye(2)
a

array([[0., 0.],
       [0., 0.]])

In [7]:
b

array([[1., 0.],
       [0., 1.]])

In [8]:
import numpy as np 

a = np.zeros((2,2))

b = np.eye(2)

In [9]:
a

array([[0., 0.],
       [0., 0.]])

In [10]:
b

array([[1., 0.],
       [0., 1.]])

In [11]:
import numpy as np 
a = np.ones(2)
b = np.ones((1,2))

In [12]:
a

array([1., 1.])

In [13]:
b

array([[1., 1.]])

In [15]:
import numpy as np
a = np.array([[1,2, 3], [4,5,6]]) 
b = a.reshape(-1)

In [16]:
b

array([1, 2, 3, 4, 5, 6])

In [17]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a[0] = a[0,::-1]
a[:,1]=a[::-1,1]

In [18]:
a

array([[ 5,  7,  3,  2,  1],
       [ 6,  4,  8,  9, 10]])

In [19]:
a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
a[-1,-1] = 0
a[a.shape[0]-2, 1] = a[0, -1] + a[-1, 0]
a[0,0]= a[0,2] + a[2,0]

In [20]:
a

array([[10,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  0]])

In [21]:
a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [23]:
a = np.matrix([[1, 0], [2, -1]])
r = a * a
r

matrix([[1, 0],
        [0, 1]])

In [24]:
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
b

array([[ 7,  8],
       [11, 12]])

In [25]:
arr = np.random.random((2,2))
arr

array([[0.64024255, 0.77721915],
       [0.30589118, 0.59819333]])

In [33]:
a = np.array([[1,2], [3,4]])
#A list comprehension 
b = [a[j,i] for i in range(a.shape[0]) for j in range(a.shape[1])]
b

[1, 3, 2, 4]

In [27]:
a = np.array([[1, 0], [2, -1]])
r = a * a
r

array([[1, 0],
       [4, 1]])

In [28]:
a = np.array([[1,2,3], [4,5,6]])
b = a.T
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [30]:
a = np. array([ [1, 2], [3, 4] ]) 
print(np.mean(a, axis=None)== np.mean(a))

True


In [31]:
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))

True


In [32]:
a = np.array( [[1,2, 3, 4],  [5,6, 7, 8],  [9,10,11,12]] )
b = a[1:3, 2:]
b

array([[ 7,  8],
       [11, 12]])

In [34]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,1], a[1,2], a[0,2])

2 6 3


In [35]:
a = np.array([[10, 11, 12]])
b = np.array([[20], [21], [22]])
c = np.array([[1,2], [3,4], [5,6]])
print(a.shape, b.shape, c.shape)

(1, 3) (3, 1) (3, 2)


In [36]:
a = np.matrix([[1, 0], [2, -1]])
r = a * a
r

matrix([[1, 0],
        [0, 1]])

In [37]:
a = np.zeros((2,2))

b = np.eye(2)

In [38]:
a

array([[0., 0.],
       [0., 0.]])

In [40]:
br

NameError: name 'br' is not defined

In [42]:
a = np.array([[1, 0], [2, -1]])
r = a * a
r

array([[1, 0],
       [4, 1]])

In [43]:
a = np.array([[1, 1], [2, 0]])
b = np.matrix(a)
I = np.identity(2)
x = a * I
y = b * I

In [44]:
x

array([[1., 0.],
       [0., 0.]])

In [45]:
y

matrix([[1., 1.],
        [2., 0.]])

In [46]:
a = np. array([ [1, 2], [3, 4] ])
print(round(np.var(a),2) == round(np.std(a)**2,2))



True


In [47]:
a = np.zeros((2,2))
b = np.eye(2)

In [48]:
a

array([[0., 0.],
       [0., 0.]])

In [49]:
b

array([[1., 0.],
       [0., 1.]])

In [51]:
a = np.ones(2)
b = np.ones((1,2))
print(a,b)

[1. 1.] [[1. 1.]]


In [53]:
a = np.array([[1,2, 3], [4,5,6]]) 
b = a.reshape(-1)
b

array([1, 2, 3, 4, 5, 6])