# Toby Sax
## week 10 - 10/24/2023
### Python numpy into

In [1]:
'''
NumPy is a Python library.
NumPy is used for working with arrays.
NumPy is short for "Numerical Python".
50x faster than traditional Python lists
'''

import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
# Dimensions in Arrays
# 0-D arrays, scalars
arr_0d = np.array(50)
print(arr_0d)

50


In [7]:
print(arr_0d, arr_0d.ndim)

50 0


In [8]:
#1-D array
# An array that has 0-D arrays as it elements

arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d, type(arr_1d), arr_1d.ndim)

[1 2 3 4 5 6] <class 'numpy.ndarray'> 1


In [9]:
#2-D array
# An array that has 1-D arrays as it elements
arr_2d = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])
print(arr_2d, arr_2d.ndim)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]] 2


In [11]:
#3-D array
# An array that has 2-D arrays as it elements
arr_3d = np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])
print(arr_3d,'\n\n', arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]] 

 3


In [12]:
len(arr_3d)

2

In [13]:
# Array Indexing
print(arr_1d)
print(arr_2d)
print(arr_3d)

[1 2 3 4 5 6]
[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [14]:
arr_1d[0]

1

In [15]:
arr_1d[-1]

6

In [16]:
arr_1d.ndim

1

In [17]:
arr_1d.shape

(6,)

In [18]:
arr_2d.ndim

2

In [19]:
arr_2d.shape

(2, 6)

In [20]:
print(arr_2d)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [21]:
arr_2d[0]

array([1, 2, 3, 4, 5, 6])

In [22]:
arr_2d[1]

array([11, 22, 33, 44, 55, 66])

In [23]:
arr_2d[1,-1]

66

In [24]:
arr_2d[0,0]

1

In [25]:
print(arr_2d)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [26]:
arr_2d[1,3]

44

In [27]:
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [28]:
arr_3d.shape

(2, 2, 3)

In [29]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr_3d[1]

array([[11, 22, 33],
       [44, 55, 66]])

In [31]:
arr_3d[1,1]

array([44, 55, 66])

In [32]:
arr_3d[1,1,-1]

66

In [33]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [34]:
arr_3d[0,1,1]

5

In [35]:
arr_3d[1,0,-1]

33

In [36]:
'''
slicing np arrays

[start:end:step] step is considered 1, end index is excluded
[start:end:step]
[:end] start at index 0
[start:] end index will be the length of the array

'''
# slicing 1-D arrays
arr_1d

array([1, 2, 3, 4, 5, 6])

In [37]:
arr_1d[:3]

array([1, 2, 3])

In [38]:
arr_1d[-3:-1]

array([4, 5])

In [39]:
arr_1d[-3:]

array([4, 5, 6])

In [40]:
arr_1d[:]

array([1, 2, 3, 4, 5, 6])

In [41]:
arr_1d[::2]

array([1, 3, 5])

In [42]:
arr_1d[::-1]

array([6, 5, 4, 3, 2, 1])

In [43]:
# 1-d is similar to slicing lists in python

In [44]:
# slicing 2-D arrays
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [45]:
arr_2d.shape

(2, 6)

In [46]:
arr_2d[0,1]

2

In [47]:
arr_2d[0,:3]

array([1, 2, 3])

In [48]:
arr_2d[1, -2:]

array([55, 66])

In [49]:
arr_2d[:,-2]

array([ 5, 55])

In [50]:
arr_2d[0:2,-2]

array([ 5, 55])

In [51]:
arr_2d[:,:2]

array([[ 1,  2],
       [11, 22]])

In [52]:
arr_2d[1,-3:]

array([44, 55, 66])

In [53]:
#3-D arrays
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [55]:
arr_3d.shape

(2, 2, 3)

In [57]:
arr_3d[1,1,1]

55

In [58]:
arr_3d[1,1,1:]

array([55, 66])

In [59]:
arr_3d[1,:,-2:]

array([[22, 33],
       [55, 66]])

In [61]:
arr_3d[:,:,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 22],
        [44, 55]]])

In [62]:
arr_3d[0,:,:2]

array([[1, 2],
       [4, 5]])

In [63]:
arr_3d[:,:,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 22],
        [44, 55]]])

In [64]:
arr = np.array([[[1,2],[4,5]],[[7,8],[10,11,3]]])

In [65]:
print(arr)

[[list([1, 2]) list([4, 5])]
 [list([7, 8]) list([10, 11, 3])]]


In [66]:
arr.shape

(2, 2)

In [67]:
arr.ndim

2

In [68]:
arr[0,1]

[4, 5]

In [69]:
type(arr[0,1])

list