# Toby Sax
## week 10 - 10/26/2023
### Python Numpy - Processing Arrays

In [1]:
import numpy as np

In [5]:
my_list = [11,22,33,44,55,66,77]
arr = np.array(my_list)
arr

array([11, 22, 33, 44, 55, 66, 77])

In [6]:
# creating an array from a nested list
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]
my_list = [lst1,lst2]
my_list

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [7]:
arr = np.array(my_list)
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [8]:
arr.ndim

2

In [9]:
arr.dtype

dtype('int32')

In [10]:
fruits = ['Orange','Apple', 'Cherry', 'Grape']

arr_str = np.array(fruits)
arr_str

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [12]:
arr_str.ndim

1

In [13]:
arr_str.dtype

dtype('<U6')

In [15]:
lst = ['Orange','Apple','Cherry','Grape',1,2,3,4,5,[6,7,8,9,10],True,False]

arr_obj = np.array(lst)
arr_obj

array(['Orange', 'Apple', 'Cherry', 'Grape', 1, 2, 3, 4, 5,
       list([6, 7, 8, 9, 10]), True, False], dtype=object)

In [16]:
arr_obj.ndim

1

In [17]:
arr_obj.dtype

dtype('O')

In [18]:
my_list

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [20]:
lst = [1,2,3,4,5]
arr = np.array(lst, dtype='S')
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [21]:
arr.dtype

dtype('S1')

In [22]:
arr = np.array(lst, dtype='i4')
arr

array([1, 2, 3, 4, 5])

In [23]:
arr.dtype

dtype('int32')

In [24]:
arr = np.array(lst, dtype='i8')
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [25]:
arr.dtype

dtype('int64')

In [26]:
# Converting Data type on existing
arr = np.array(['1','2','3','4','5'], dtype = 'i')
arr

array([1, 2, 3, 4, 5], dtype=int32)

In [27]:
scores = [78.5,88.9,90.3,889.9,89.67]
arr = np.array(scores)
arr

array([ 78.5 ,  88.9 ,  90.3 , 889.9 ,  89.67])

In [34]:
arr.dtype

dtype('float64')

In [35]:
arr_int = arr.astype('i')
arr_int

array([ 78,  88,  90, 889,  89], dtype=int32)

In [36]:
arr_int.dtype

dtype('int32')

In [37]:
print(arr)

[ 78.5   88.9   90.3  889.9   89.67]


In [39]:
arr.dtype

dtype('float64')

In [40]:
lst = [1,0,1,1,0,0,1,0,0,1,0,0]
arr = np.array(lst)
arr

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [41]:
arr.dtype

dtype('int32')

In [42]:
arr_bool = arr.astype(bool)
arr_bool

array([ True, False,  True,  True, False, False,  True, False, False,
        True, False, False])

In [43]:
arr_bool.dtype

dtype('bool')

In [44]:
arr

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0])

In [45]:
# NumPy array copy vs view, vs = with the list
lst = [1,2,3,4,5]
lst_e = lst


In [46]:
lst

[1, 2, 3, 4, 5]

In [47]:
lst_e

[1, 2, 3, 4, 5]

In [48]:
lst[0] = 55

In [49]:
lst

[55, 2, 3, 4, 5]

In [50]:
lst_e

[55, 2, 3, 4, 5]

In [51]:
arr = np.array(lst)
arr

array([55,  2,  3,  4,  5])

In [52]:
arr_c = arr.copy()
arr_c

array([55,  2,  3,  4,  5])

In [53]:
#the copy is a new array
arr

array([55,  2,  3,  4,  5])

In [54]:
arr_c

array([55,  2,  3,  4,  5])

In [55]:
arr[0] = 11
print(arr)
print(arr_c)

[11  2  3  4  5]
[55  2  3  4  5]


In [56]:
arr_c[-1]=0
print(arr)
print(arr_c)

[11  2  3  4  5]
[55  2  3  4  0]


In [57]:
lst = [11,12,13,14,15]
arr = np.array(lst)
arr_v = arr.view() # view is just a view of the original array

In [58]:
print(arr)
print(arr_v)

[11 12 13 14 15]
[11 12 13 14 15]


In [59]:
arr[-1] = 55
print(arr)
print(arr_v)

[11 12 13 14 55]
[11 12 13 14 55]


In [60]:
arr[0] = 88
print(arr)
print(arr_v)

[88 12 13 14 55]
[88 12 13 14 55]


In [61]:
arr_v[0] = 11
print(arr)
print(arr_v)

[11 12 13 14 55]
[11 12 13 14 55]


In [63]:
print(arr_v.base)
print(arr_c.base)

[11 12 13 14 55]
None


In [64]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]
arr = np.array(my_list)
arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [65]:
arr.ndim

2

In [66]:
arr.shape

(2, 5)

In [67]:
arr = np.array(lst1)
arr

array([1, 2, 3, 4, 5])

In [68]:
arr.ndim

1

In [69]:
arr.shape

(5,)

In [70]:
arr = np.array(lst1, ndmin=4)
arr

array([[[[1, 2, 3, 4, 5]]]])

In [71]:
arr.ndim

4

In [72]:
arr.shape

(1, 1, 1, 5)

In [73]:
arr = np.array(lst1, ndmin=6)
arr

array([[[[[[1, 2, 3, 4, 5]]]]]])

In [74]:
arr.ndim

6

In [75]:
arr.shape

(1, 1, 1, 1, 1, 5)

In [77]:
arr.shape[0]

1

In [78]:
arr = np.array([[2,3,4,5],[6,7,8,9]])
arr.shape

(2, 4)

In [79]:
arr[0][1]

3

In [80]:
arr.shape[0]

2

In [81]:
arr.shape[1]

4

In [82]:
arr

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [83]:
# reading data from files
f = open("data.txt","w")
f.write("1, 2, 3\n")
f.write("4, 5, 6\n")
f.close()

#read
f = open("data.txt","r")
print(f.read())

1, 2, 3
4, 5, 6



In [84]:
arr = np.genfromtxt("data.txt", dtype=None, delimiter=",")
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
arr.dtype

dtype('int32')

In [88]:
arr = np.loadtxt("data1.txt", dtype=int)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])