# Toby Sax
## 11/2/2023 - week 11
### Python NumPy Universal Functions

In [1]:
import numpy as np
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [5]:
arr = np.random.randn(10) # return a sample (or sample) from the "standard normal" distribution.
arr

array([-0.56174788,  0.8653754 ,  1.71817017,  0.19296248, -2.74522118,
       -0.7783709 , -1.17674202,  0.4097311 , -2.03509852, -0.79143787])

In [6]:
arr.mean()

-0.49023792117142956

In [7]:
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)

In [8]:
arr1

array([ 1.06748052, -0.11706369,  0.20910801,  1.61134554,  0.51097238,
        0.95381609,  1.70792547, -0.37509412,  0.10356674, -0.31657991])

In [9]:
arr2

array([-2.12621900e-04, -4.18257557e-01,  4.74651822e-01, -2.81839307e-01,
       -1.42312329e-01, -1.59653465e+00,  1.55381741e+00, -8.35093841e-02,
       -5.48510456e-01,  7.33059517e-01])

In [10]:
np.add(arr1,arr2) #add arguments element-wise

array([ 1.06726789, -0.53532125,  0.68375984,  1.32950623,  0.36866006,
       -0.64271856,  3.26174288, -0.45860351, -0.44494372,  0.41647961])

In [11]:
#maximum
np.maximum(arr1,arr2)

array([ 1.06748052, -0.11706369,  0.47465182,  1.61134554,  0.51097238,
        0.95381609,  1.70792547, -0.08350938,  0.10356674,  0.73305952])

In [14]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.ones(9).reshape(3,3)

In [15]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.add(arr1,arr2)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
#array filtering
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [20]:
# using where
#replace values of an array, using where
np.where(arr < 4, 0, -1)

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [21]:
np.where((arr < 4)&(arr > 2),0,-1)

array([[-1, -1, -1],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [29]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_bool = [True, False, True, False,True]
arr1


array([1, 2, 3, 4, 5])

In [30]:
arr2

array([10, 20, 30, 40, 50])

In [31]:
arr_bool

[True, False, True, False, True]

In [32]:
list(zip(arr1,arr2,arr_bool))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, False), (5, 50, True)]

In [33]:
#using list comprehension
arr = np.array([r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_bool)])
arr

array([ 1, 20,  3, 40,  5])

In [35]:
arr = np.where(arr_bool, arr1, arr2)
arr

array([ 1, 20,  3, 40,  5])

In [1]:
import numpy as np
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [2]:
arr2

array([[5, 6],
       [7, 8]])

In [9]:
sample_bool = [True, False]
arr_bool = np.random.choice(sample_bool, 10)
arr_bool

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [10]:
arr1

array([[1, 2],
       [3, 4]])

In [11]:
arr2

array([[5, 6],
       [7, 8]])

In [12]:
arr_bool = np.array([np.random.choice(sample_bool, size=2),np.random.choice(sample_bool, size=2)])
arr_bool

array([[False,  True],
       [False,  True]])

In [17]:
arr_bool = np.random.choice(sample_bool, size=4).reshape(2,2)

In [18]:
arr_bool

array([[ True,  True],
       [ True,  True]])

In [19]:
np.where(arr_bool, arr1,arr2)

array([[1, 2],
       [3, 4]])

In [20]:
arr = np.random.randn(3,3)
arr

array([[ 1.69360445, -1.63115216,  1.68558777],
       [-1.12966195,  1.29413776, -0.20832859],
       [-0.99259794,  2.11098814, -0.4854469 ]])

In [21]:
np.where(arr<0, 0,arr)

array([[1.69360445, 0.        , 1.68558777],
       [0.        , 1.29413776, 0.        ],
       [0.        , 2.11098814, 0.        ]])

In [23]:
# any 
arr_bool = np.random.choice(sample_bool, size=10)
arr_bool

array([False, False, False,  True, False,  True, False,  True, False,
        True])

In [24]:
arr_bool.any() # returns true if all elements evaluate to true

True

In [25]:
arr_bool.all() # returns true if all of the elements of array evasluate to true

False

In [26]:
# unique() finds the unique=e elements of an array.
fruits = np.array([['Apple', 'Cherry', 'Apple','Orange','Cherry','Banana']])
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [27]:
#test whether each elemnt of a 1-D arraty is also present in a secound
np.in1d(['Apple','Cherry',"Grape"],fruits)

array([ True,  True, False])

In [28]:
fruits

array([['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana']],
      dtype='<U6')

In [29]:
'Apple' in fruits

True

In [30]:
#descriptive statistical measuers
arr_2d = np.arange(1,10).reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr_2d.shape

(3, 3)

In [32]:
arr_2d.ndim

2

In [33]:
arr_2d.sum()

45

In [34]:
#axis0
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr_2d.sum(0)

array([12, 15, 18])

In [36]:
arr_2d.sum(1)

array([ 6, 15, 24])

In [37]:
np.sum(arr_2d, axis=0)

array([12, 15, 18])

In [38]:
np.sum(arr_2d, axis=1)

array([ 6, 15, 24])

In [40]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr_2d.mean()

5.0

In [42]:
arr_2d.mean(0)

array([4., 5., 6.])

In [43]:
arr_2d.mean(1)

array([2., 5., 8.])

In [45]:
np.mean(arr_2d, axis=0)

array([4., 5., 6.])

In [46]:
np.mean(arr_2d, axis=1)

array([2., 5., 8.])

In [47]:
arr_2d.var()

6.666666666666667

In [48]:
arr_2d.var(0)

array([6., 6., 6.])

In [49]:
arr_2d.var(1)

array([0.66666667, 0.66666667, 0.66666667])

In [50]:
np.var(arr_2d, axis=0)

array([6., 6., 6.])

In [51]:
np.var(arr_2d, axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [52]:
arr = np.random.randn(3,3)
arr

array([[-1.0622222 ,  0.12744825,  1.23069905],
       [ 0.24726103,  0.82853982, -2.87945995],
       [-0.68836627, -0.77147462,  0.93117013]])

In [53]:
from numpy.random import randn
arr = randn(3,3)
arr

array([[ 0.39646854,  0.72279155,  0.21021537],
       [ 0.42818839,  0.54015319,  0.22453221],
       [ 2.2051359 , -0.36157648, -0.25309252]])

In [57]:
arr = np.random.random((4,4))
arr

array([[0.84675372, 0.07915228, 0.60135585, 0.74171837],
       [0.15632213, 0.97374586, 0.71462429, 0.27372643],
       [0.36104205, 0.1288489 , 0.44277231, 0.623796  ],
       [0.88230556, 0.37115452, 0.58827575, 0.88345787]])

In [58]:
from numpy.random import random
arr = random((4,4))
arr

array([[0.23159339, 0.6179586 , 0.38511186, 0.05360078],
       [0.3575581 , 0.13485775, 0.87389557, 0.9111976 ],
       [0.19911671, 0.64539979, 0.30419467, 0.48916889],
       [0.04090277, 0.37059851, 0.67653505, 0.26217456]])

In [60]:
num = np.random.randint(10,50)
num

33

In [65]:
arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

In [66]:
arr1

array([1, 2, 3])

In [67]:
arr2

array([4, 5, 6])

In [68]:
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [69]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [70]:
arr1

array([[1, 2],
       [3, 4]])

In [71]:
arr2

array([[5, 6],
       [7, 8]])

In [72]:
arr = np.concatenate((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
arr.shape

(4, 2)

In [74]:
arr1.shape

(2, 2)

In [79]:
arr = np.concatenate((arr1,arr2), axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [80]:
arr = np.concatenate((arr1,arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [81]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [82]:
narr = np.split(arr, 2)
narr

[array([1, 2, 3]), array([4, 5, 6])]

In [83]:
narr[0]

array([1, 2, 3])

In [84]:
narr[1]

array([4, 5, 6])

In [85]:
narr = np.split(arr, 3)
narr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [88]:
narr = np.split(arr, 4)
narr

ValueError: array split does not result in an equal division

In [89]:
narr = np.array_split(arr, 4)
narr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [90]:
narr[0]

array([1, 2])

In [92]:
narr[-1]

array([6])