# Toby Sax
## 11/2/2023 - week 11
### Python numpy creating

In [1]:
import numpy as np

In [3]:
#.T same as self.transpose(),
arr = np.arange(45).reshape(9,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [4]:
arr.shape

(9, 5)

In [5]:
arr.ndim

2

In [6]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [7]:
arr.T.shape

(5, 9)

In [9]:
arr_t = arr.T

In [10]:
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [11]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [12]:
arr[0] = 100
arr

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44]])

In [13]:
arr_t

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [14]:
np.transpose(arr)

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [15]:
np.transpose(arr).shape

(5, 9)

In [16]:
arr.transpose()

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [17]:
arr = np.arange(8).reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
arr.shape

(2, 4)

In [19]:
arr.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [21]:
arr.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [22]:
arr.shape[0]

2

In [23]:
arr.shape[1]

4

In [24]:
arr.transpose((0,1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
arr.transpose((1,0)) #swap axis 0 with axis 1

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [27]:
arr_3d = np.arange(20).reshape(2,5,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [28]:
arr_3d.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [29]:
arr_3d.T.shape

(2, 5, 2)

In [32]:
arr_3d.transpose()

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [33]:
arr_3d.transpose().shape

(2, 5, 2)

In [35]:
arr_3d.transpose((0,1,2)) #no change in the axis, same order

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [38]:
arr_3d.transpose((1,0,2)) # change axis0 with axis1

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [39]:
arr_3d.transpose((1,0,2)).shape

(5, 2, 2)

In [40]:
arr_3d.transpose((1,2,0))

array([[[ 0, 10],
        [ 1, 11]],

       [[ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17]],

       [[ 8, 18],
        [ 9, 19]]])

In [41]:
arr_3d.transpose((1,2,0)).shape

(5, 2, 2)

In [42]:
arr_3d.transpose((0,2,1))

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]]])

In [43]:
arr_3d.transpose((0,2,1)).shape

(2, 2, 5)

In [44]:
#swapaxes 
arr = np.array([[1,2,3,4]])
arr

array([[1, 2, 3, 4]])

In [45]:
arr.ndim

2

In [46]:
arr.shape

(1, 4)

In [47]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3],
       [4]])

In [48]:
arr

array([[1, 2, 3, 4]])

In [49]:
arr.swapaxes(0,1).shape

(4, 1)

In [50]:
arr_3d = np.arange(45).reshape(3,5,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [51]:
arr_3d.ndim

3

In [52]:
arr_3d.shape

(3, 5, 3)

In [53]:
arr_3d.swapaxes(1,2)

array([[[ 0,  3,  6,  9, 12],
        [ 1,  4,  7, 10, 13],
        [ 2,  5,  8, 11, 14]],

       [[15, 18, 21, 24, 27],
        [16, 19, 22, 25, 28],
        [17, 20, 23, 26, 29]],

       [[30, 33, 36, 39, 42],
        [31, 34, 37, 40, 43],
        [32, 35, 38, 41, 44]]])

In [54]:
arr_3d.swapaxes(1,2).shape

(3, 3, 5)

In [56]:
arr_3d.swapaxes(0,1)

array([[[ 0,  1,  2],
        [15, 16, 17],
        [30, 31, 32]],

       [[ 3,  4,  5],
        [18, 19, 20],
        [33, 34, 35]],

       [[ 6,  7,  8],
        [21, 22, 23],
        [36, 37, 38]],

       [[ 9, 10, 11],
        [24, 25, 26],
        [39, 40, 41]],

       [[12, 13, 14],
        [27, 28, 29],
        [42, 43, 44]]])

In [57]:
arr_3d.swapaxes(0,1).shape

(5, 3, 3)

In [58]:
arr_3d.swapaxes(2,1)

array([[[ 0,  3,  6,  9, 12],
        [ 1,  4,  7, 10, 13],
        [ 2,  5,  8, 11, 14]],

       [[15, 18, 21, 24, 27],
        [16, 19, 22, 25, 28],
        [17, 20, 23, 26, 29]],

       [[30, 33, 36, 39, 42],
        [31, 34, 37, 40, 43],
        [32, 35, 38, 41, 44]]])

In [59]:
arr_3d[0] = 100

In [60]:
arr_3d

array([[[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29]],

       [[ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]]])

In [61]:
arr_3d.swapaxes(1,2)

array([[[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]],

       [[ 15,  18,  21,  24,  27],
        [ 16,  19,  22,  25,  28],
        [ 17,  20,  23,  26,  29]],

       [[ 30,  33,  36,  39,  42],
        [ 31,  34,  37,  40,  43],
        [ 32,  35,  38,  41,  44]]])